// import React from 'react'

// const Index = () => {
//   return (
//     <html>

//     <head></head>
    
//     <body data-new-gr-c-s-check-loaded="14.1176.0" data-gr-ext-installed="" style={{cursor: 'auto', background: 'rgb(17, 17, 17) none repeat scroll 0% 0% / auto padding-box border-box', -token83776693E5554dff8ca60d4ab718fb22: 'rgb(17, 17, 17)', -token954291aa4b264810Bff067a06b776cfa: 'rgb(28, 28, 28)', -tokenDd1cc2c8830044ac89ad0993e4945ff1: 'rgba(255, 255, 255, .25)', -tokenDebbb7ea54064bf9B0ce2dc7ec3c94d4: 'rgba(255, 255, 255, .5)', -token3e056f5cDd104d668cbc41785b3871d7: 'rgb(255, 255, 255)', fontSize: '12px', fontFamily: 'sans-serif', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', margin: '0px', padding: '0px'}}>
//         {/* End of bodyStart */}
//         <div data-framer-hydrate-v2="{&quot;routeId&quot;:&quot;augiA20Il&quot;,&quot;localeId&quot;:&quot;default&quot;,&quot;breakpoints&quot;:[{&quot;hash&quot;:&quot;72rtr7&quot;,&quot;mediaQuery&quot;:&quot;(min-width: 1280px)&quot;},{&quot;hash&quot;:&quot;1q662xi&quot;,&quot;mediaQuery&quot;:&quot;(min-width: 810px) and (max-width: 1279px)&quot;},{&quot;hash&quot;:&quot;bpeyfo&quot;,&quot;mediaQuery&quot;:&quot;(max-width: 809px)&quot;}]}" data-framer-ssr-released-at="2024-05-24T13:31:44.927Z" data-framer-page-optimized-at="2024-05-29T06:33:52.235Z" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased', margin: '0px', padding: '0px'}}>
//             {/*$*/}
//             <div style={{minHeight: '100vh', width: 'autoplace-content:center flex-start', alignItems: 'center', backgroundColor: 'rgb(17, 17, 17)', display: 'flex', flexFlow: 'column nowrap', gap: '120px', height: '6269.45px', overflow: 'visible', padding: '0px', position: 'relative', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                 <div data-framer-name="main" name="main" style={{placeContent: 'center flex-start', alignItems: 'center', display: 'flex', flex: '0 0 auto', flexFlow: 'column nowrap', gap: '120px', height: '5250.86px', maxWidth: '1216px', overflow: 'visible', padding: '24px 0px 0px', position: 'relative', width: '100%', zIndex: 1, boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                     <div data-framer-name="header+hero" name="header+hero" style={{placeContent: 'center', alignItems: 'center', display: 'flex', flex: '0 0 auto', flexFlow: 'column nowrap', gap: '80px', height: '834.969px', overflow: 'visible', padding: '0px', position: 'relative', width: '100%', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
                        
                       
//                     </div>

                    
                   
//                     <div data-border="true" data-framer-name="services" name="services" style={{-borderBottomWidth: '0px', -borderColor: 1, -borderLeftWidth: '0px', -borderRightWidth: '0px', -borderStyle: 'solid', -borderTopWidth: '1px', placeContent: 'flex-start', alignItems: 'flex-start', borderRadius: '100px', display: 'flex', flex: '0 0 auto', flexFlow: 'column nowrap', gap: '40px', height: '742.359px', overflow: 'visible', padding: '40px 40px 0px', position: 'relative', width: '100%', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                         <div data-framer-name="h3" name="h3" style={{flex: '0 0 auto', height: 'auto', position: 'relative', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                             <div name="h3" data-border="true" data-framer-name="h3" style={{-borderBottomWidth: '0px', -borderColor: 'var(--token-dd1cc2c8-8300-44ac-89ad-0993e4945ff1, rgba(255, 255, 255, 0.5))', -borderLeftWidth: '0px', -borderRightWidth: '0px', -borderStyle: 'solid', -borderTopWidth: '1px', backdropFilter: 'blur(0px)', backgroundColor: 'rgb(28, 28, 28)', borderRadius: '100px', opacity: 1, placeContent: 'center', alignItems: 'center', display: 'flex', flexFlow: 'row nowrap', gap: '8px', height: '52.7969px', overflow: 'visible', padding: '12px 32px', position: 'relative', width: 'min-content', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} tabIndex="0">
//                                 <div style={{outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0, -framerParagraphSpacing: '0px', transform: 'none', opacity: 1, position: 'relative', flex: '0 0 auto', height: 'auto', whiteSpace: 'pre', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-component-type="RichTextContainer">
//                                     <h3 data-styles-preset="HcfNbDYIm" style={{fontFamily: 'Inter, "Inter Placeholder", sans-serif', fontStyle: 'normal', fontWeight: 400, color: 'rgb(255, 255, 255)', fontSize: '18px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(255, 255, 255)', lineHeight: '28.8px', textAlign: 'center', WebkitTextStrokeWidth: '0px', WebkitTextStrokeColor: 'rgb(255, 255, 255)', margin: '0px', padding: '0px', -framerFontFamily: '"Inter", "Inter Placeholder", sans-serif', -framerFontFamilyBold: '"Inter", "Inter Placeholder", sans-serif', -framerFontSize: '18px', -framerFontStyle: 'normal', -framerFontStyleBold: 'normal', -framerFontWeight: 400, -framerFontWeightBold: 700, -framerLetterSpacing: '0em', -framerLineHeight: '160%', -framerParagraphSpacing: '40px', -framerTextAlignment: 'center', -framerTextColor: 1, -framerTextDecoration: 'none', -framerTextTransform: 'none', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>My Services</h3>
//                                 </div>
//                             </div>
//                         </div>
//                         <div data-framer-name="services" name="services" style={{placeContent: 'flex-start', alignItems: 'flex-start', display: 'flex', flex: '0 0 auto', flexFlow: 'column nowrap', gap: '24px', height: '609.562px', overflow: 'visible', padding: '0px', position: 'relative', width: '100%', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                             <div data-border="true" data-framer-name="service_card" name="service_card" style={{-borderBottomWidth: '0px', -borderColor: '1)', -borderLeftWidth: '0px', -borderRightWidth: '0px', -borderStyle: 'solid', -borderTopWidth: '1px', placeContent: 'flex-start space-between', alignItems: 'flex-start', backdropFilter: 'blur(0px)', backgroundColor: 'rgb(28, 28, 28)', borderRadius: '24px', display: 'flex', flex: '0 0 auto', flexFlow: 'row nowrap', height: '134.391px', overflow: 'visible', padding: '24px', position: 'relative', width: '100%', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                                 <div data-framer-name="01. Web Design" style={{outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0, transform: 'noneposition:relative', -framerParagraphSpacing: '0px', flex: '0 0 auto', height: 'auto', position: 'relative', whiteSpace: 'pre', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-component-type="RichTextContainer">
//                                     <h2 data-styles-preset="lLJY8ro9R" style={{fontFamily: 'Inter, "Inter Placeholder", sans-serif', fontStyle: 'normal', fontWeight: 500, color: 'rgb(255, 255, 255)', fontSize: '24px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(255, 255, 255)', lineHeight: '38.4px', textAlign: 'start', WebkitTextStrokeWidth: '0px', WebkitTextStrokeColor: 'rgb(255, 255, 255)', margin: '0px', padding: '0px', -framerFontFamily: '"Inter", "Inter Placeholder", sans-serif', -framerFontFamilyBold: '"Inter", "Inter Placeholder", sans-serif', -framerFontSize: '24px', -framerFontStyle: 'normal', -framerFontStyleBold: 'normal', -framerFontWeight: 500, -framerFontWeightBold: 700, -framerLetterSpacing: '0em', -framerLineHeight: '160%', -framerParagraphSpacing: '40px', -framerTextAlignment: 'start', -framerTextColor: '#ffffff', -framerTextDecoration: 'none', -framerTextTransform: 'none', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>01. Web Design</h2>
//                                 </div>
//                                 <div data-framer-name="Crafting visually compelling and user-friendly websites is at the core of what I do. I specialize in creating modern and elegant designs that not only captivate audiences but also effectively communicate your brand message." style={{outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0, transform: 'noneposition:relative', -framerParagraphSpacing: '0px', flex: '0 0 auto', height: 'auto', position: 'relative', whiteSpace: 'pre-wrap', width: '544px', wordBreak: 'break-word', overflowWrap: 'break-word', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-component-type="RichTextContainer">
//                                     <p data-styles-preset="ZVGBVyoFG" style={{-framerTextColor: 'var(--token-3e056f5c-dd10-4d66-8cbc-41785b3871d7, rgb(255, 255, 255))font-family:Inter, sans-serif', fontStyle: 'normal', fontWeight: 400, color: 'rgb(255, 255, 255)', fontSize: '18px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(255, 255, 255)', lineHeight: '28.8px', textAlign: 'start', WebkitTextStrokeWidth: '0px', WebkitTextStrokeColor: 'rgb(255, 255, 255)', margin: '0px', padding: '0px', -framerFontFamily: '"Inter", sans-serif', -framerFontFamilyBold: '"Inter", "Inter Placeholder", sans-serif', -framerFontFamilyBoldItalic: '"Inter", "Inter Placeholder", sans-serif', -framerFontFamilyItalic: '"Inter", "Inter Placeholder", sans-serif', -framerFontSize: '18px', -framerFontStyle: 'normal', -framerFontStyleBold: 'normal', -framerFontStyleBoldItalic: 'italic', -framerFontStyleItalic: 'italic', -framerFontWeight: 400, -framerFontWeightBold: 700, -framerFontWeightBoldItalic: 700, -framerFontWeightItalic: 400, -framerLetterSpacing: '0em', -framerLineHeight: '160%', -framerParagraphSpacing: '16px', -framerTextAlignment: 'start', -framerTextDecoration: 'none', -framerTextTransform: 'none', fontFamily: 'Inter, sans-serif', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>I specialize in creating modern and elegant designs that not only captivate audiences but also effectively communicate your brand message.</p>
//                                 </div>
//                             </div>
//                             <div data-border="true" data-framer-name="service_card" name="service_card" style={{-borderBottomWidth: '0px', -borderColor: '1)', -borderLeftWidth: '0px', -borderRightWidth: '0px', -borderStyle: 'solid', -borderTopWidth: '1px', placeContent: 'flex-start space-between', alignItems: 'flex-start', backdropFilter: 'blur(0px)', backgroundColor: 'rgb(28, 28, 28)', borderRadius: '24px', display: 'flex', flex: '0 0 auto', flexFlow: 'row nowrap', height: '134.391px', overflow: 'visible', padding: '24px', position: 'relative', width: '100%', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                                 <div data-framer-name="01. Web Design" style={{outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0, transform: 'noneposition:relative', -framerParagraphSpacing: '0px', flex: '0 0 auto', height: 'auto', position: 'relative', whiteSpace: 'pre', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-component-type="RichTextContainer">
//                                     <h2 data-styles-preset="lLJY8ro9R" style={{fontFamily: 'Inter, "Inter Placeholder", sans-serif', fontStyle: 'normal', fontWeight: 500, color: 'rgb(255, 255, 255)', fontSize: '24px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(255, 255, 255)', lineHeight: '38.4px', textAlign: 'start', WebkitTextStrokeWidth: '0px', WebkitTextStrokeColor: 'rgb(255, 255, 255)', margin: '0px', padding: '0px', -framerFontFamily: '"Inter", "Inter Placeholder", sans-serif', -framerFontFamilyBold: '"Inter", "Inter Placeholder", sans-serif', -framerFontSize: '24px', -framerFontStyle: 'normal', -framerFontStyleBold: 'normal', -framerFontWeight: 500, -framerFontWeightBold: 700, -framerLetterSpacing: '0em', -framerLineHeight: '160%', -framerParagraphSpacing: '40px', -framerTextAlignment: 'start', -framerTextColor: '#ffffff', -framerTextDecoration: 'none', -framerTextTransform: 'none', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>02. Web Development</h2>
//                                 </div>
//                                 <div data-framer-name="Crafting visually compelling and user-friendly websites is at the core of what I do. I specialize in creating modern and elegant designs that not only captivate audiences but also effectively communicate your brand message." style={{outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0, transform: 'noneposition:relative', -framerParagraphSpacing: '0px', flex: '0 0 auto', height: 'auto', position: 'relative', whiteSpace: 'pre-wrap', width: '544px', wordBreak: 'break-word', overflowWrap: 'break-word', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-component-type="RichTextContainer">
//                                     <p data-styles-preset="ZVGBVyoFG" style={{-framerTextColor: 'var(--token-3e056f5c-dd10-4d66-8cbc-41785b3871d7, rgb(255, 255, 255))font-family:Inter, sans-serif', fontStyle: 'normal', fontWeight: 400, color: 'rgb(255, 255, 255)', fontSize: '18px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(255, 255, 255)', lineHeight: '28.8px', textAlign: 'start', WebkitTextStrokeWidth: '0px', WebkitTextStrokeColor: 'rgb(255, 255, 255)', margin: '0px', padding: '0px', -framerFontFamily: '"Inter", sans-serif', -framerFontFamilyBold: '"Inter", "Inter Placeholder", sans-serif', -framerFontFamilyBoldItalic: '"Inter", "Inter Placeholder", sans-serif', -framerFontFamilyItalic: '"Inter", "Inter Placeholder", sans-serif', -framerFontSize: '18px', -framerFontStyle: 'normal', -framerFontStyleBold: 'normal', -framerFontStyleBoldItalic: 'italic', -framerFontStyleItalic: 'italic', -framerFontWeight: 400, -framerFontWeightBold: 700, -framerFontWeightBoldItalic: 700, -framerFontWeightItalic: 400, -framerLetterSpacing: '0em', -framerLineHeight: '160%', -framerParagraphSpacing: '16px', -framerTextAlignment: 'start', -framerTextDecoration: 'none', -framerTextTransform: 'none', fontFamily: 'Inter, sans-serif', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>With proficiency in HTML, CSS, JavaScript, and various development frameworks, I bring your vision to life with pixel-perfect precision.</p>
//                                 </div>
//                             </div>
//                             <div data-border="true" data-framer-name="service_card" name="service_card" style={{-borderBottomWidth: '0px', -borderColor: '1)', -borderLeftWidth: '0px', -borderRightWidth: '0px', -borderStyle: 'solid', -borderTopWidth: '1px', placeContent: 'flex-start space-between', alignItems: 'flex-start', backdropFilter: 'blur(0px)', backgroundColor: 'rgb(28, 28, 28)', borderRadius: '24px', display: 'flex', flex: '0 0 auto', flexFlow: 'row nowrap', height: '134.391px', overflow: 'visible', padding: '24px', position: 'relative', width: '100%', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                                 <div data-framer-name="01. Web Design" style={{outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0, transform: 'noneposition:relative', -framerParagraphSpacing: '0px', flex: '0 0 auto', height: 'auto', position: 'relative', whiteSpace: 'pre', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-component-type="RichTextContainer">
//                                     <h2 data-styles-preset="lLJY8ro9R" style={{fontFamily: 'Inter, "Inter Placeholder", sans-serif', fontStyle: 'normal', fontWeight: 500, color: 'rgb(255, 255, 255)', fontSize: '24px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(255, 255, 255)', lineHeight: '38.4px', textAlign: 'start', WebkitTextStrokeWidth: '0px', WebkitTextStrokeColor: 'rgb(255, 255, 255)', margin: '0px', padding: '0px', -framerFontFamily: '"Inter", "Inter Placeholder", sans-serif', -framerFontFamilyBold: '"Inter", "Inter Placeholder", sans-serif', -framerFontSize: '24px', -framerFontStyle: 'normal', -framerFontStyleBold: 'normal', -framerFontWeight: 500, -framerFontWeightBold: 700, -framerLetterSpacing: '0em', -framerLineHeight: '160%', -framerParagraphSpacing: '40px', -framerTextAlignment: 'start', -framerTextColor: '#ffffff', -framerTextDecoration: 'none', -framerTextTransform: 'none', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>03. Graphic Design</h2>
//                                 </div>
//                                 <div data-framer-name="Crafting visually compelling and user-friendly websites is at the core of what I do. I specialize in creating modern and elegant designs that not only captivate audiences but also effectively communicate your brand message." style={{outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0, transform: 'noneposition:relative', -framerParagraphSpacing: '0px', flex: '0 0 auto', height: 'auto', position: 'relative', whiteSpace: 'pre-wrap', width: '544px', wordBreak: 'break-word', overflowWrap: 'break-word', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-component-type="RichTextContainer">
//                                     <p data-styles-preset="ZVGBVyoFG" style={{-framerTextColor: 'var(--token-3e056f5c-dd10-4d66-8cbc-41785b3871d7, rgb(255, 255, 255))font-family:Inter, sans-serif', fontStyle: 'normal', fontWeight: 400, color: 'rgb(255, 255, 255)', fontSize: '18px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(255, 255, 255)', lineHeight: '28.8px', textAlign: 'start', WebkitTextStrokeWidth: '0px', WebkitTextStrokeColor: 'rgb(255, 255, 255)', margin: '0px', padding: '0px', -framerFontFamily: '"Inter", sans-serif', -framerFontFamilyBold: '"Inter", "Inter Placeholder", sans-serif', -framerFontFamilyBoldItalic: '"Inter", "Inter Placeholder", sans-serif', -framerFontFamilyItalic: '"Inter", "Inter Placeholder", sans-serif', -framerFontSize: '18px', -framerFontStyle: 'normal', -framerFontStyleBold: 'normal', -framerFontStyleBoldItalic: 'italic', -framerFontStyleItalic: 'italic', -framerFontWeight: 400, -framerFontWeightBold: 700, -framerFontWeightBoldItalic: 700, -framerFontWeightItalic: 400, -framerLetterSpacing: '0em', -framerLineHeight: '160%', -framerParagraphSpacing: '16px', -framerTextAlignment: 'start', -framerTextDecoration: 'none', -framerTextTransform: 'none', fontFamily: 'Inter, sans-serif', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>I specialize in creating impactful visual assets that reflect the unique personality and core values of your brand, ensuring a memorable and authentic representation.</p>
//                                 </div>
//                             </div>
//                             <div data-border="true" data-framer-name="service_card" name="service_card" style={{-borderBottomWidth: '0px', -borderColor: '1)', -borderLeftWidth: '0px', -borderRightWidth: '0px', -borderStyle: 'solid', -borderTopWidth: '1px', placeContent: 'flex-start space-between', alignItems: 'flex-start', backdropFilter: 'blur(0px)', backgroundColor: 'rgb(28, 28, 28)', borderRadius: '24px', display: 'flex', flex: '0 0 auto', flexFlow: 'row nowrap', height: '134.391px', overflow: 'visible', padding: '24px', position: 'relative', width: '100%', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                                 <div data-framer-name="01. Web Design" style={{outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0, transform: 'noneposition:relative', -framerParagraphSpacing: '0px', flex: '0 0 auto', height: 'auto', position: 'relative', whiteSpace: 'pre', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-component-type="RichTextContainer">
//                                     <h2 data-styles-preset="lLJY8ro9R" style={{fontFamily: 'Inter, "Inter Placeholder", sans-serif', fontStyle: 'normal', fontWeight: 500, color: 'rgb(255, 255, 255)', fontSize: '24px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(255, 255, 255)', lineHeight: '38.4px', textAlign: 'start', WebkitTextStrokeWidth: '0px', WebkitTextStrokeColor: 'rgb(255, 255, 255)', margin: '0px', padding: '0px', -framerFontFamily: '"Inter", "Inter Placeholder", sans-serif', -framerFontFamilyBold: '"Inter", "Inter Placeholder", sans-serif', -framerFontSize: '24px', -framerFontStyle: 'normal', -framerFontStyleBold: 'normal', -framerFontWeight: 500, -framerFontWeightBold: 700, -framerLetterSpacing: '0em', -framerLineHeight: '160%', -framerParagraphSpacing: '40px', -framerTextAlignment: 'start', -framerTextColor: '#ffffff', -framerTextDecoration: 'none', -framerTextTransform: 'none', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>04. Website Maintenance</h2>
//                                 </div>
//                                 <div data-framer-name="Crafting visually compelling and user-friendly websites is at the core of what I do. I specialize in creating modern and elegant designs that not only captivate audiences but also effectively communicate your brand message." style={{outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0, transform: 'noneposition:relative', -framerParagraphSpacing: '0px', flex: '0 0 auto', height: 'auto', position: 'relative', whiteSpace: 'pre-wrap', width: '544px', wordBreak: 'break-word', overflowWrap: 'break-word', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-component-type="RichTextContainer">
//                                     <p data-styles-preset="ZVGBVyoFG" style={{-framerTextColor: 'var(--token-3e056f5c-dd10-4d66-8cbc-41785b3871d7, rgb(255, 255, 255))font-family:Inter, sans-serif', fontStyle: 'normal', fontWeight: 400, color: 'rgb(255, 255, 255)', fontSize: '18px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(255, 255, 255)', lineHeight: '28.8px', textAlign: 'start', WebkitTextStrokeWidth: '0px', WebkitTextStrokeColor: 'rgb(255, 255, 255)', margin: '0px', padding: '0px', -framerFontFamily: '"Inter", sans-serif', -framerFontFamilyBold: '"Inter", "Inter Placeholder", sans-serif', -framerFontFamilyBoldItalic: '"Inter", "Inter Placeholder", sans-serif', -framerFontFamilyItalic: '"Inter", "Inter Placeholder", sans-serif', -framerFontSize: '18px', -framerFontStyle: 'normal', -framerFontStyleBold: 'normal', -framerFontStyleBoldItalic: 'italic', -framerFontStyleItalic: 'italic', -framerFontWeight: 400, -framerFontWeightBold: 700, -framerFontWeightBoldItalic: 700, -framerFontWeightItalic: 400, -framerLetterSpacing: '0em', -framerLineHeight: '160%', -framerParagraphSpacing: '16px', -framerTextAlignment: 'start', -framerTextDecoration: 'none', -framerTextTransform: 'none', fontFamily: 'Inter, sans-serif', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>With my comprehensive website maintenance and support services, you can trust that your online presence is expertly cared for, allowing you to focus on what matters most.</p>
//                                 </div>
//                             </div>
//                         </div>
//                     </div>
//                 </div>
//                 <div data-framer-name="cta+footer" name="cta+footer" style={{placeContent: 'center flex-start', alignItems: 'center', display: 'flex', flex: '0 0 auto', flexFlow: 'column nowrap', gap: '40px', height: '898.594px', overflow: 'visible', padding: '0px', position: 'relative', width: '100%', zIndex: 1, boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                     <div style={{flex: '0 0 auto', height: 'auto', position: 'relative', width: '100%', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                         <div style={{display: 'contents', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                             <div data-framer-name="Desktop" style={{borderRadius: '24px', width: '100%', opacity: 1, placeContent: 'center', alignItems: 'center', display: 'flex', flexFlow: 'column nowrap', gap: '24px', height: '700px', overflow: 'visible', padding: '0px', position: 'relative', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} tabIndex="0">
//                                 <div style={{position: 'absolute', borderRadius: 'inherit', top: 0, right: 0, bottom: 0, left: '0box-sizing:border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-background-image-wrapper="true"><img decoding="async" sizes="100vw" srcSet="https://framerusercontent.com/images/Gxph3eQdeqhXa5dHw5c0NykhSE.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/Gxph3eQdeqhXa5dHw5c0NykhSE.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/Gxph3eQdeqhXa5dHw5c0NykhSE.jpg?scale-down-to=2048 2048w,https://framerusercontent.com/images/Gxph3eQdeqhXa5dHw5c0NykhSE.jpg 3840w" src="https://framerusercontent.com/images/Gxph3eQdeqhXa5dHw5c0NykhSE.jpg" alt="" style={{display: 'block', width: '100%', height: '100%', borderRadius: 'inherit', objectPosition: 'center', objectFit: 'cover', imageRendering: 'autobox-sizing:border-box', WebkitFontSmoothing: 'antialiased'}} /></div>
//                                 <div style={{opacity: 1, flex: '0 0 auto', height: 'auto', position: 'relative', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}><a data-framer-name="top_dotted" data-highlight="true" style={{backgroundColor: 'rgba(77, 77, 77, 0.1)', borderRadius: '118px', opacity: 1, placeContent: 'center', alignItems: 'center', cursor: 'pointer', display: 'flex', flexFlow: 'row nowrap', gap: '12px', height: 'auto', overflow: 'visible', padding: '16px 32px', position: 'relative', textDecoration: 'none solid rgb(0, 0, 238)', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} href="./contact" tabIndex="0">
//                                         <div data-framer-name="Glow" style={{background: 'radial-gradient(25% 47.8908% at 43.4641% 8.57917%, rgb(255, 255, 255) 0%, rgba(255, 255, 255, 0) 100%)', borderRadius: '72px', filter: 'blur(15px)', opacity: 1, flex: '0 0 auto', inset: '0px', overflow: 'hidden', position: 'absolute', willChange: 'transform', zIndex: 0, boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></div>
//                                         <div data-framer-name="Stroke" style={{background: 'radial-gradient(20.1441% 49.0617% at 43.4641% 8.57917%, rgb(255, 255, 255) 0%, rgba(255, 255, 255, 0) 100%)', borderRadius: '72px', opacity: 1, flex: '0 0 auto', inset: '0px', overflow: 'hidden', position: 'absolute', willChange: 'transform', zIndex: 0, boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></div>
//                                         <div data-framer-name="Fill" style={{backgroundColor: 'rgba(28, 28, 28, 0.9)', borderRadius: '114px', opacity: 1, placeContent: 'center', alignItems: 'center', display: 'flex', flex: '0 0 auto', flexFlow: 'row nowrap', gap: '10px', inset: '2px', overflow: 'hidden', padding: '0px', position: 'absolute', willChange: 'transform', zIndex: 0, boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></div>
//                                         <div data-framer-name="dot" style={{opacity: 1, transform: 'matrix(-0.250119, -0.771992, 0.771992, -0.250119, 0, 0)', flex: '0 0 auto', height: '12px', overflow: 'visible', position: 'relative', width: '12px', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                                             <div data-framer-name="Ellipse 2" style={{backgroundColor: 'rgba(75, 207, 31, 0.25)', borderRadius: '100%', opacity: 1, aspectRatio: '1 / 1', flex: '0 0 auto', height: '16px', left: '-2px', position: 'absolute', right: '-2px', top: '-2px', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></div>
//                                             <div data-framer-name="Ellipse 1" style={{backgroundColor: 'rgb(75, 207, 31)', borderRadius: '100%', transform: 'matrix(1, 0, 0, 1, -4, -4)', opacity: 1, aspectRatio: '1 / 1', flex: '0 0 auto', height: '8px', left: '6px', position: 'absolute', top: '6px', width: '8px', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></div>
//                                         </div>
//                                         <div style={{outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0, -extractedR6o4lv: 'var(--token-3e056f5c-dd10-4d66-8cbc-41785b3871d7, rgb(255, 255, 255))', transform: 'none', opacity: 1, position: 'relative', flex: '0 0 auto', height: 'auto', whiteSpace: 'pre', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-component-type="RichTextContainer">
//                                             <p data-styles-preset="ZVGBVyoFG" style={{-framerTextColor: 'var(--extracted-r6o4lv, var(--token-3e056f5c-dd10-4d66-8cbc-41785b3871d7, rgb(255, 255, 255)))font-family:Inter, sans-serif', fontStyle: 'normal', fontWeight: 400, color: 'rgb(255, 255, 255)', fontSize: '18px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(255, 255, 255)', lineHeight: '28.8px', textAlign: 'start', WebkitTextStrokeWidth: '0px', WebkitTextStrokeColor: 'rgb(255, 255, 255)', margin: '0px', padding: '0px', -framerFontFamily: '"Inter", sans-serif', -framerFontFamilyBold: '"Inter", "Inter Placeholder", sans-serif', -framerFontFamilyBoldItalic: '"Inter", "Inter Placeholder", sans-serif', -framerFontFamilyItalic: '"Inter", "Inter Placeholder", sans-serif', -framerFontSize: '18px', -framerFontStyle: 'normal', -framerFontStyleBold: 'normal', -framerFontStyleBoldItalic: 'italic', -framerFontStyleItalic: 'italic', -framerFontWeight: 400, -framerFontWeightBold: 700, -framerFontWeightBoldItalic: 700, -framerFontWeightItalic: 400, -framerLetterSpacing: '0em', -framerLineHeight: '160%', -framerParagraphSpacing: '16px', -framerTextAlignment: 'start', -framerTextDecoration: 'none', -framerTextTransform: 'none', fontFamily: 'Inter, sans-serif', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>Available For Work</p>
//                                         </div>
//                                     </a></div>
//                                 <div style={{opacity: 1, flex: '0 0 auto', height: 'auto', position: 'relative', width: '100%', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                                     <div data-framer-name="Desktop" style={{width: '100%', opacity: 1, cursor: 'pointer', height: '96px', overflow: 'hidden', position: 'relative', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} tabIndex="0"><a href="mailto:yourname@example.com" rel="noopener" style={{opacity: 1, placeContent: 'center', alignItems: 'center', display: 'flex', flex: '0 0 auto', flexFlow: 'column nowrap', gap: '0px', height: '192px', left: '0px', overflow: 'visible', padding: '0px', position: 'absolute', right: '0px', textDecoration: 'none solid rgb(0, 0, 238)', top: '0px', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                                             <div style={{outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0, -framerParagraphSpacing: '0px', transform: 'none', opacity: 1, position: 'relative', flex: '0 0 auto', height: 'auto', whiteSpace: 'pre-wrap', width: '1280px', wordBreak: 'break-word', overflowWrap: 'break-word', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-component-type="RichTextContainer">
//                                                 <p data-styles-preset="CmGuxCZg3" style={{fontFamily: 'Inter, "Inter Placeholder", sans-serif', fontStyle: 'normal', fontWeight: 700, color: 'rgb(255, 255, 255)', fontSize: '80px', letterSpacing: 'normal', textTransform: 'uppercase', textDecoration: 'none solid rgb(255, 255, 255)', lineHeight: '96px', textAlign: 'center', WebkitTextStrokeWidth: '0px', WebkitTextStrokeColor: 'rgb(255, 255, 255)', margin: '0px', padding: '0px', -framerFontFamily: '"Inter", "Inter Placeholder", sans-serif', -framerFontFamilyBold: '"Inter", sans-serif', -framerFontSize: '80px', -framerFontStyle: 'normal', -framerFontStyleBold: 'normal', -framerFontWeight: 700, -framerFontWeightBold: 900, -framerLetterSpacing: '0em', -framerLineHeight: '120%', -framerParagraphSpacing: '20px', -framerTextAlignment: 'center', -framerTextColor: 1, -framerTextDecoration: 'none', -framerTextTransform: 'uppercase', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>molfar@gmail.com</p>
//                                             </div>
//                                             <div style={{outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0, -extractedTcooor: 'rgb(255, 255, 255)', -framerParagraphSpacing: '0px', opacity: '0.6', transform: 'noneposition:relative', flex: '0 0 auto', height: 'auto', position: 'relative', whiteSpace: 'pre-wrap', width: '100%', wordBreak: 'break-word', overflowWrap: 'break-word', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-component-type="RichTextContainer">
//                                                 <div style={{-fontSelector: 'R0Y7SW50ZXItNzAw', -framerFontFamily: '&quot', -framerFontSize: '80px', -framerFontWeight: 700, -framerLineHeight: '120%', -framerTextAlignment: 'center', -framerTextColor: 'var(--extracted-tcooor, rgb(255, 255, 255))', -framerTextTransform: 'uppercasefont-family:Inter, "Inter Placeholder", sans-serif', fontStyle: 'normal', fontWeight: 700, color: 'rgb(255, 255, 255)', fontSize: '80px', letterSpacing: 'normal', textTransform: 'uppercase', textDecoration: 'none solid rgb(255, 255, 255)', lineHeight: '96px', textAlign: 'center', WebkitTextStrokeWidth: '0px', WebkitTextStrokeColor: 'rgb(255, 255, 255)', margin: '0px', padding: '0px', fontFamily: 'Inter, "Inter Placeholder", sans-serif', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>molfar@gmail.com</div>
//                                             </div>
//                                         </a></div>
//                                 </div>
//                             </div>
//                         </div>
//                     </div>
//                     <div style={{flex: '0 0 auto', height: 'auto', position: 'relative', width: '100%', zIndex: 1, boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                         <div style={{display: 'contents', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                             <div data-framer-name="desktop" style={{width: '100%', opacity: 1, placeContent: 'center flex-start', alignItems: 'center', display: 'flex', flexFlow: 'column nowrap', gap: '40px', height: '158.594px', overflow: 'visible', padding: '0px 0px 40px', position: 'relative', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} tabIndex="0">
//                                 <div data-framer-name="footer" style={{opacity: 1, placeContent: 'center', alignItems: 'center', display: 'flex', flex: '0 0 auto', flexFlow: 'column nowrap', gap: '24px', height: '118.594px', maxWidth: '1216px', overflow: 'visible', padding: '0px', position: 'relative', width: '100%', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                                     <div data-framer-name="top-info" style={{opacity: 1, placeContent: 'center space-between', alignItems: 'center', display: 'flex', flex: '0 0 auto', flexFlow: 'row nowrap', height: '42px', overflow: 'visible', padding: '0px', position: 'relative', width: '100%', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}><a data-framer-name="Molfar" href="./" data-framer-page-link-current="true" style={{opacity: 1, fontFamily: 'Inter, "Inter Placeholder", sans-serif', fontStyle: 'normal', fontWeight: 400, color: 'rgb(0, 0, 0)', fontSize: '16px', textTransform: 'none', textDecoration: 'none solid rgb(0, 0, 0)', aspectRatio: '5.10526 / 1', flex: '0 0 auto', height: '19px', overflow: 'visible', position: 'relative', width: '97px', display: 'block', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                                             <div data-framer-background-image-wrapper="true" style={{position: 'absolute', borderRadius: '0px', inset: '0px', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}><img decoding="async" src="https://framerusercontent.com/images/2JIgalejcmrUKEz5JwwdnjEupE.svg" alt="Logo" style={{display: 'block', width: '100%', height: '19px', borderRadius: '0px', objectPosition: '50% 50%', objectFit: 'cover', imageRendering: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} /></div>
//                                         </a>
//                                         <div data-framer-name="nav" style={{transform: 'translate(-50%, -50%)', opacity: 1, placeContent: 'flex-start', alignItems: 'flex-start', display: 'flex', flex: '0 0 auto', flexFlow: 'row nowrap', gap: '8px', height: '41.5938px', left: '608px', overflow: 'visible', padding: '0px', position: 'absolute', top: '21px', width: 'min-content', zIndex: 1, boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                                             <div style={{opacity: 1, flex: '0 0 auto', height: 'auto', position: 'relative', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}><a data-border="true" data-framer-name="Desktop" style={{-borderBottomWidth: '1px', -borderColor: 'var(--token-3e056f5c-dd10-4d66-8cbc-41785b3871d7, rgb(255, 255, 255))', -borderLeftWidth: '1px', -borderRightWidth: '1px', -borderStyle: 'solid', -borderTopWidth: '1px', backgroundColor: 'rgba(0, 0, 0, 0)', borderRadius: '100px', opacity: 1, placeContent: 'center', alignItems: 'center', cursor: 'pointer', display: 'flex', flexFlow: 'row nowrap', gap: '10px', height: '41.5938px', overflow: 'visible', padding: '8px 16px', position: 'relative', textDecoration: 'none solid rgb(0, 0, 238)', width: 'min-content', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} href="./" tabIndex="0">
//                                                     <div style={{outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0, -extractedR6o4lv: 'var(--token-3e056f5c-dd10-4d66-8cbc-41785b3871d7, rgb(255, 255, 255))', -framerParagraphSpacing: '0px', transform: 'none', opacity: 1, position: 'relative', flex: '0 0 auto', height: 'auto', whiteSpace: 'pre', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-component-type="RichTextContainer">
//                                                         <p data-styles-preset="FKXgixZ2m" style={{-framerTextColor: 'var(--extracted-r6o4lv, var(--token-3e056f5c-dd10-4d66-8cbc-41785b3871d7, rgb(255, 255, 255)))font-family:Inter, "Inter Placeholder", sans-serif', fontStyle: 'normal', fontWeight: 400, color: 'rgb(255, 255, 255)', fontSize: '16px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(255, 255, 255)', lineHeight: '25.6px', textAlign: 'center', WebkitTextStrokeWidth: '0px', WebkitTextStrokeColor: 'rgb(255, 255, 255)', margin: '0px', padding: '0px', -framerFontFamily: '"Inter", "Inter Placeholder", sans-serif', -framerFontFamilyBold: '"Inter", "Inter Placeholder", sans-serif', -framerFontSize: '16px', -framerFontStyle: 'normal', -framerFontStyleBold: 'normal', -framerFontWeight: 400, -framerFontWeightBold: 700, -framerLetterSpacing: '0em', -framerLineHeight: '160%', -framerParagraphSpacing: '20px', -framerTextAlignment: 'center', -framerTextDecoration: 'none', -framerTextTransform: 'none', fontFamily: 'Inter, "Inter Placeholder", sans-serif', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>Home</p>
//                                                     </div>
//                                                 </a></div>
//                                             <div style={{opacity: 1, flex: '0 0 auto', height: 'auto', position: 'relative', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}><a data-border="true" data-framer-name="Desktop" style={{-borderBottomWidth: '1px', -borderColor: 'var(--token-3e056f5c-dd10-4d66-8cbc-41785b3871d7, rgb(255, 255, 255))', -borderLeftWidth: '1px', -borderRightWidth: '1px', -borderStyle: 'solid', -borderTopWidth: '1px', backgroundColor: 'rgba(0, 0, 0, 0)', borderRadius: '100px', opacity: 1, placeContent: 'center', alignItems: 'center', cursor: 'pointer', display: 'flex', flexFlow: 'row nowrap', gap: '10px', height: '41.5938px', overflow: 'visible', padding: '8px 16px', position: 'relative', textDecoration: 'none solid rgb(0, 0, 238)', width: 'min-content', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} href="./about" tabIndex="0">
//                                                     <div style={{outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0, -extractedR6o4lv: 'var(--token-3e056f5c-dd10-4d66-8cbc-41785b3871d7, rgb(255, 255, 255))', -framerParagraphSpacing: '0px', transform: 'none', opacity: 1, position: 'relative', flex: '0 0 auto', height: 'auto', whiteSpace: 'pre', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-component-type="RichTextContainer">
//                                                         <p data-styles-preset="FKXgixZ2m" style={{-framerTextColor: 'var(--extracted-r6o4lv, var(--token-3e056f5c-dd10-4d66-8cbc-41785b3871d7, rgb(255, 255, 255)))font-family:Inter, "Inter Placeholder", sans-serif', fontStyle: 'normal', fontWeight: 400, color: 'rgb(255, 255, 255)', fontSize: '16px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(255, 255, 255)', lineHeight: '25.6px', textAlign: 'center', WebkitTextStrokeWidth: '0px', WebkitTextStrokeColor: 'rgb(255, 255, 255)', margin: '0px', padding: '0px', -framerFontFamily: '"Inter", "Inter Placeholder", sans-serif', -framerFontFamilyBold: '"Inter", "Inter Placeholder", sans-serif', -framerFontSize: '16px', -framerFontStyle: 'normal', -framerFontStyleBold: 'normal', -framerFontWeight: 400, -framerFontWeightBold: 700, -framerLetterSpacing: '0em', -framerLineHeight: '160%', -framerParagraphSpacing: '20px', -framerTextAlignment: 'center', -framerTextDecoration: 'none', -framerTextTransform: 'none', fontFamily: 'Inter, "Inter Placeholder", sans-serif', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>About</p>
//                                                     </div>
//                                                 </a></div>
//                                             <div style={{opacity: 1, flex: '0 0 auto', height: 'auto', position: 'relative', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}><a data-border="true" data-framer-name="Desktop" style={{-borderBottomWidth: '1px', -borderColor: 'var(--token-3e056f5c-dd10-4d66-8cbc-41785b3871d7, rgb(255, 255, 255))', -borderLeftWidth: '1px', -borderRightWidth: '1px', -borderStyle: 'solid', -borderTopWidth: '1px', backgroundColor: 'rgba(0, 0, 0, 0)', borderRadius: '100px', opacity: 1, placeContent: 'center', alignItems: 'center', cursor: 'pointer', display: 'flex', flexFlow: 'row nowrap', gap: '10px', height: '41.5938px', overflow: 'visible', padding: '8px 16px', position: 'relative', textDecoration: 'none solid rgb(0, 0, 238)', width: 'min-content', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} href="./portfolio" tabIndex="0">
//                                                     <div style={{outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0, -extractedR6o4lv: 'var(--token-3e056f5c-dd10-4d66-8cbc-41785b3871d7, rgb(255, 255, 255))', -framerParagraphSpacing: '0px', transform: 'none', opacity: 1, position: 'relative', flex: '0 0 auto', height: 'auto', whiteSpace: 'pre', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-component-type="RichTextContainer">
//                                                         <p data-styles-preset="FKXgixZ2m" style={{-framerTextColor: 'var(--extracted-r6o4lv, var(--token-3e056f5c-dd10-4d66-8cbc-41785b3871d7, rgb(255, 255, 255)))font-family:Inter, "Inter Placeholder", sans-serif', fontStyle: 'normal', fontWeight: 400, color: 'rgb(255, 255, 255)', fontSize: '16px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(255, 255, 255)', lineHeight: '25.6px', textAlign: 'center', WebkitTextStrokeWidth: '0px', WebkitTextStrokeColor: 'rgb(255, 255, 255)', margin: '0px', padding: '0px', -framerFontFamily: '"Inter", "Inter Placeholder", sans-serif', -framerFontFamilyBold: '"Inter", "Inter Placeholder", sans-serif', -framerFontSize: '16px', -framerFontStyle: 'normal', -framerFontStyleBold: 'normal', -framerFontWeight: 400, -framerFontWeightBold: 700, -framerLetterSpacing: '0em', -framerLineHeight: '160%', -framerParagraphSpacing: '20px', -framerTextAlignment: 'center', -framerTextDecoration: 'none', -framerTextTransform: 'none', fontFamily: 'Inter, "Inter Placeholder", sans-serif', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>Portfolio</p>
//                                                     </div>
//                                                 </a></div>
//                                             <div style={{opacity: 1, flex: '0 0 auto', height: 'auto', position: 'relative', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}><a data-border="true" data-framer-name="Desktop" style={{-borderBottomWidth: '1px', -borderColor: 'var(--token-3e056f5c-dd10-4d66-8cbc-41785b3871d7, rgb(255, 255, 255))', -borderLeftWidth: '1px', -borderRightWidth: '1px', -borderStyle: 'solid', -borderTopWidth: '1px', backgroundColor: 'rgba(0, 0, 0, 0)', borderRadius: '100px', opacity: 1, placeContent: 'center', alignItems: 'center', cursor: 'pointer', display: 'flex', flexFlow: 'row nowrap', gap: '10px', height: '41.5938px', overflow: 'visible', padding: '8px 16px', position: 'relative', textDecoration: 'none solid rgb(0, 0, 238)', width: 'min-content', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} href="./contact" tabIndex="0">
//                                                     <div style={{outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0, -extractedR6o4lv: 'var(--token-3e056f5c-dd10-4d66-8cbc-41785b3871d7, rgb(255, 255, 255))', -framerParagraphSpacing: '0px', transform: 'none', opacity: 1, position: 'relative', flex: '0 0 auto', height: 'auto', whiteSpace: 'pre', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-component-type="RichTextContainer">
//                                                         <p data-styles-preset="FKXgixZ2m" style={{-framerTextColor: 'var(--extracted-r6o4lv, var(--token-3e056f5c-dd10-4d66-8cbc-41785b3871d7, rgb(255, 255, 255)))font-family:Inter, "Inter Placeholder", sans-serif', fontStyle: 'normal', fontWeight: 400, color: 'rgb(255, 255, 255)', fontSize: '16px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(255, 255, 255)', lineHeight: '25.6px', textAlign: 'center', WebkitTextStrokeWidth: '0px', WebkitTextStrokeColor: 'rgb(255, 255, 255)', margin: '0px', padding: '0px', -framerFontFamily: '"Inter", "Inter Placeholder", sans-serif', -framerFontFamilyBold: '"Inter", "Inter Placeholder", sans-serif', -framerFontSize: '16px', -framerFontStyle: 'normal', -framerFontStyleBold: 'normal', -framerFontWeight: 400, -framerFontWeightBold: 700, -framerLetterSpacing: '0em', -framerLineHeight: '160%', -framerParagraphSpacing: '20px', -framerTextAlignment: 'center', -framerTextDecoration: 'none', -framerTextTransform: 'none', fontFamily: 'Inter, "Inter Placeholder", sans-serif', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>Contact</p>
//                                                     </div>
//                                                 </a></div>
//                                         </div>
//                                         <div data-framer-name="socials" style={{opacity: 1, placeContent: 'center', alignItems: 'center', display: 'flex', flex: '0 0 auto', flexFlow: 'row nowrap', gap: '24px', height: '24px', overflow: 'visible', padding: '0px', position: 'relative', width: 'min-content', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                                             <div data-framer-name="x" name="x" style={{opacity: 1, flex: '0 0 auto', height: '24px', position: 'relative', width: '24px', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}><a name="x" aria-label="X/Twitter" data-framer-name="x" style={{height: '100%', width: '100%', opacity: '1cursor:pointer', overflow: 'hidden', position: 'relative', textDecoration: 'none solid rgb(0, 0, 238)', display: 'block', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} href="https://x.com" target="_blank" rel="noopener" tabIndex="0">
//                                                     <div data-framer-component-type="SVG" data-framer-name="x" style={{imageRendering: 'pixelated', flexShrink: 0, fill: 'rgb(0, 0, 0)', color: 'rgb(0, 0, 0)', opacity: 1, position: 'absolute', aspectRatio: '1 / 1', flex: '0 0 auto', height: '24px', left: '0px', right: '0px', top: '0px', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                                                         <div style={{width: '100%', height: '100%', aspectRatio: 'inheritbox-sizing:border-box', WebkitFontSmoothing: 'antialiased'}}><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style={{width: '100%', height: '100%height:24px', display: 'block', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} viewBox="0 0 24 24" preserveAspectRatio="none" width="100%" height="100%">
//                                                                 <use href="#svg-1785960115_279" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></use>
//                                                             </svg></div>
//                                                     </div>
//                                                 </a></div>
//                                             <div style={{opacity: 1, flex: '0 0 auto', height: '24px', position: 'relative', width: '24px', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}><a aria-label="Instagram" data-framer-name="inst" style={{height: '100%', width: '100%', opacity: '1cursor:pointer', overflow: 'hidden', position: 'relative', textDecoration: 'none solid rgb(0, 0, 238)', display: 'block', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} href="https://instagram.com" target="_blank" rel="noopener" tabIndex="0">
//                                                     <div data-framer-component-type="SVG" data-framer-name="inst" style={{imageRendering: 'pixelated', flexShrink: 0, fill: 'rgb(0, 0, 0)', color: 'rgb(0, 0, 0)', opacity: 1, position: 'absolute', aspectRatio: '1 / 1', flex: '0 0 auto', height: '24px', left: '0px', right: '0px', top: '0px', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                                                         <div style={{width: '100%', height: '100%', aspectRatio: 'inheritbox-sizing:border-box', WebkitFontSmoothing: 'antialiased'}}><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style={{width: '100%', height: '100%height:24px', display: 'block', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} viewBox="0 0 24 24" preserveAspectRatio="none" width="100%" height="100%">
//                                                                 <use href="#svg1883355575_1857" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></use>
//                                                             </svg></div>
//                                                     </div>
//                                                 </a></div>
//                                         </div>
//                                     </div>
//                                     <div data-framer-name="bottom-info" style={{opacity: 1, placeContent: 'center', alignItems: 'center', display: 'flex', flex: '0 0 auto', flexFlow: 'column nowrap', gap: '24px', height: '52.5938px', overflow: 'hidden', padding: '0px', position: 'relative', width: '100%', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                                         <div data-framer-name="info" style={{opacity: 1, placeContent: 'flex-start space-between', alignItems: 'flex-start', display: 'flex', flex: '0 0 auto', flexFlow: 'row nowrap', height: '25.5938px', overflow: 'visible', padding: '0px', position: 'relative', width: '100%', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                                             <div style={{outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0, -extracted1w3ko1f: 'var(--token-debbb7ea-5406-4bf9-b0ce-2dc7ec3c94d4, rgba(255, 255, 255, 0.5))', -extractedR6o4lv: 'var(--token-3e056f5c-dd10-4d66-8cbc-41785b3871d7, rgb(255, 255, 255))', -framerParagraphSpacing: '0px', transform: 'none', opacity: 1, position: 'relative', flex: '0 0 auto', height: 'auto', whiteSpace: 'pre', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-component-type="RichTextContainer">
//                                                 <p data-styles-preset="FKXgixZ2m" style={{-framerTextColor: 'var(--extracted-r6o4lv, var(--token-3e056f5c-dd10-4d66-8cbc-41785b3871d7, rgb(255, 255, 255)))font-family:Inter, "Inter Placeholder", sans-serif', fontStyle: 'normal', fontWeight: 400, color: 'rgb(255, 255, 255)', fontSize: '16px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgb(255, 255, 255)', lineHeight: '25.6px', textAlign: 'center', WebkitTextStrokeWidth: '0px', WebkitTextStrokeColor: 'rgb(255, 255, 255)', margin: '0px', padding: '0px', -framerFontFamily: '"Inter", "Inter Placeholder", sans-serif', -framerFontFamilyBold: '"Inter", "Inter Placeholder", sans-serif', -framerFontSize: '16px', -framerFontStyle: 'normal', -framerFontStyleBold: 'normal', -framerFontWeight: 400, -framerFontWeightBold: 700, -framerLetterSpacing: '0em', -framerLineHeight: '160%', -framerParagraphSpacing: '20px', -framerTextAlignment: 'center', -framerTextDecoration: 'none', -framerTextTransform: 'none', fontFamily: 'Inter, "Inter Placeholder", sans-serif', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}><span style={{-framerTextColor: 'var(--extracted-1w3ko1f, var(--token-debbb7ea-5406-4bf9-b0ce-2dc7ec3c94d4, rgba(255, 255, 255, 0.5)))font-family:Inter, "Inter Placeholder", sans-serif', fontStyle: 'normal', fontWeight: 400, color: 'rgba(255, 255, 255, 0.5)', fontSize: '16px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgba(255, 255, 255, 0.5)', lineHeight: '25.6px', textAlign: 'center', WebkitTextStrokeWidth: '0px', WebkitTextStrokeColor: 'rgba(255, 255, 255, 0.5)', fontFamily: 'Inter, "Inter Placeholder", sans-serif', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>Created by </span><a data-styles-preset="cqpBdOmEx" href="https://twitter.com/boucheedesign" target="_blank" rel="noopener" style={{fontFamily: 'Inter, "Inter Placeholder", sans-serif', fontStyle: 'normal', fontWeight: 400, color: 'rgb(255, 255, 255)', fontSize: '16px', textTransform: 'none', textDecoration: 'underline solid rgb(255, 255, 255)', cursor: 'pointer', -framerLinkCurrentTextColor: '#ffffff', -framerLinkCurrentTextDecoration: 'underline', -framerLinkHoverTextColor: '1)', -framerLinkHoverTextDecoration: 'none', -framerLinkTextColor: '#ffffff', -framerLinkTextDecoration: 'underline', transition: 'color 0.2s cubic-bezier(0.44, 0, 0.56, 1) 0s', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>boucheedesign</a></p>
//                                             </div>
//                                             <div style={{outline: 'none', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', flexShrink: 0, -extractedHl0iuy: 'var(--token-3e056f5c-dd10-4d66-8cbc-41785b3871d7, rgb(255, 255, 255))', -extractedR6o4lv: 'var(--token-debbb7ea-5406-4bf9-b0ce-2dc7ec3c94d4, rgba(255, 255, 255, 0.4))', -framerParagraphSpacing: '0px', transform: 'none', opacity: 1, position: 'relative', flex: '0 0 auto', height: 'auto', whiteSpace: 'pre', width: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}} data-framer-component-type="RichTextContainer">
//                                                 <p data-styles-preset="FKXgixZ2m" style={{-framerTextColor: 'var(--extracted-r6o4lv, var(--token-debbb7ea-5406-4bf9-b0ce-2dc7ec3c94d4, rgba(255, 255, 255, 0.4)))font-family:Inter, "Inter Placeholder", sans-serif', fontStyle: 'normal', fontWeight: 400, color: 'rgba(255, 255, 255, 0.5)', fontSize: '16px', letterSpacing: 'normal', textTransform: 'none', textDecoration: 'none solid rgba(255, 255, 255, 0.5)', lineHeight: '25.6px', textAlign: 'center', WebkitTextStrokeWidth: '0px', WebkitTextStrokeColor: 'rgba(255, 255, 255, 0.5)', margin: '0px', padding: '0px', -framerFontFamily: '"Inter", "Inter Placeholder", sans-serif', -framerFontFamilyBold: '"Inter", "Inter Placeholder", sans-serif', -framerFontSize: '16px', -framerFontStyle: 'normal', -framerFontStyleBold: 'normal', -framerFontWeight: 400, -framerFontWeightBold: 700, -framerLetterSpacing: '0em', -framerLineHeight: '160%', -framerParagraphSpacing: '20px', -framerTextAlignment: 'center', -framerTextDecoration: 'none', -framerTextTransform: 'none', fontFamily: 'Inter, "Inter Placeholder", sans-serif', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>Built in <a data-styles-preset="cqpBdOmEx" href="https://www.framer.com?via=boucheedesign" target="_blank" rel="noopener" style={{fontFamily: 'Inter, "Inter Placeholder", sans-serif', fontStyle: 'normal', fontWeight: 400, color: 'rgb(255, 255, 255)', fontSize: '16px', textTransform: 'none', textDecoration: 'underline solid rgb(255, 255, 255)', cursor: 'pointer', -framerLinkCurrentTextColor: '#ffffff', -framerLinkCurrentTextDecoration: 'underline', -framerLinkHoverTextColor: '1)', -framerLinkHoverTextDecoration: 'none', -framerLinkTextColor: '#ffffff', -framerLinkTextDecoration: 'underline', transition: 'color 0.2s cubic-bezier(0.44, 0, 0.56, 1) 0s', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}><span style={{-framerTextColor: 'var(--extracted-hl0iuy, var(--token-3e056f5c-dd10-4d66-8cbc-41785b3871d7, rgb(255, 255, 255)))font-family:Inter, "Inter Placeholder", sans-serif', fontStyle: 'normal', fontWeight: 400, color: 'rgb(255, 255, 255)', fontSize: '16px', textTransform: 'none', textDecoration: 'underline solid rgb(255, 255, 255)', cursor: 'pointer', fontFamily: 'Inter, "Inter Placeholder", sans-serif', letterSpacing: 'normal', lineHeight: '25.6px', textAlign: 'center', WebkitTextStrokeWidth: '0px', WebkitTextStrokeColor: 'rgb(255, 255, 255)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>Framer</span></a></p>
//                                             </div>
//                                         </div>
//                                     </div>
//                                 </div>
//                             </div>
//                         </div>
//                     </div>
//                 </div>
//                 <div data-framer-name="grain" name="grain" style={{flex: '0 0 auto', height: '6269.45px', left: '0px', opacity: '0.05', pointerEvents: 'none', position: 'absolute', top: '0px', width: '100%', zIndex: 0, boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                     <div style={{width: '100%', height: '100%', position: 'relative', overflow: 'hiddenbox-sizing:border-box', WebkitFontSmoothing: 'antialiased'}}>
//                         <div style={{background: 'url(&quot', https: '//framerusercontent.com/images/rR6HYXBrMmX4cRpXfXUOvpvpB0.png&quot', opacity: '0.05', inset: '-12538.9px -3806px', width: '400%', height: '25077.8px', position: 'absolute', transform: 'matrix(1, 0, 0, 1, -974.336, 501.556)', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></div>
//                     </div>
//                 </div>
//                 <div data-framer-name="smooth scroll" name="smooth scroll" style={{flex: '0 0 auto', height: '6269.45px', left: '0px', position: 'absolute', top: '0px', width: '100%', zIndex: 0, boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></div>
//             </div>
//             <div style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></div>
//             {/*/$*/}
//         </div>
//         <div style={{position: 'absolute', overflow: 'hidden', top: '0px', left: '0px', width: 0, height: '0px', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//             <div style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                 <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                     <path d="M0 0h24v24H0z" stroke="none" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></path>
//                     <path d="M5 12h14m-6 6 6-6m-6-6 6 6" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></path>
//                 </svg>
//             </div>
//             <div style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                 <svg width="24" height="24" fill="none" xmlns="http://www.w3.org/2000/svg" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                     <path d="M18.326 1.904H21.7l-7.37 8.423L23 21.79h-6.789l-5.317-6.952L4.81 21.79H1.434l7.883-9.01L1 1.904h6.961l4.806 6.354 5.56-6.354ZM17.142 19.77h1.87L6.945 3.817H4.94L17.142 19.77Z" fill="#fff" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></path>
//                 </svg>
//             </div>
//             <div style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                 <svg width="24" height="24" fill="none" xmlns="http://www.w3.org/2000/svg" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                     <g clip-path="url(#svg1883355575_1857_a)" fill="#fff" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                         <path d="M12 2.16c3.206 0 3.586.015 4.847.071 1.172.052 1.805.249 2.226.413a3.71 3.71 0 0 1 1.379.895c.421.422.68.82.895 1.378.164.422.36 1.06.412 2.227.057 1.265.07 1.645.07 4.847 0 3.206-.013 3.586-.07 4.846-.051 1.172-.248 1.805-.412 2.227a3.714 3.714 0 0 1-.895 1.378 3.69 3.69 0 0 1-1.379.895c-.421.165-1.059.361-2.226.413-1.266.056-1.645.07-4.847.07-3.206 0-3.586-.014-4.847-.07-1.172-.052-1.805-.248-2.226-.413a3.71 3.71 0 0 1-1.379-.895 3.691 3.691 0 0 1-.895-1.378c-.164-.422-.36-1.06-.412-2.227-.057-1.265-.07-1.645-.07-4.846 0-3.207.013-3.586.07-4.847.051-1.172.248-1.805.412-2.227.216-.558.478-.96.895-1.378.422-.422.82-.68 1.379-.895.421-.164 1.059-.361 2.226-.413 1.261-.056 1.64-.07 4.847-.07ZM12 0C8.742 0 8.334.014 7.055.07 5.78.127 4.903.333 4.144.628a5.857 5.857 0 0 0-2.128 1.388A5.88 5.88 0 0 0 .628 4.139C.333 4.903.127 5.775.07 7.05.014 8.334 0 8.742 0 12s.014 3.666.07 4.945c.057 1.275.263 2.152.558 2.911.31.792.717 1.463 1.388 2.128a5.866 5.866 0 0 0 2.123 1.383c.764.296 1.636.502 2.911.558 1.28.056 1.688.07 4.945.07 3.258 0 3.666-.014 4.946-.07 1.275-.056 2.151-.262 2.91-.558a5.866 5.866 0 0 0 2.124-1.383 5.866 5.866 0 0 0 1.383-2.123c.295-.764.501-1.636.558-2.911.056-1.28.07-1.688.07-4.945 0-3.258-.014-3.666-.07-4.946-.057-1.275-.263-2.151-.558-2.91a5.62 5.62 0 0 0-1.374-2.133A5.866 5.866 0 0 0 19.861.633C19.097.338 18.225.13 16.95.075 15.666.015 15.258 0 12 0Z" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></path>
//                         <path d="M12 5.836A6.166 6.166 0 0 0 5.836 12 6.166 6.166 0 0 0 12 18.164 6.166 6.166 0 0 0 18.164 12 6.166 6.166 0 0 0 12 5.836Zm0 10.162A3.999 3.999 0 1 1 12.001 8 3.999 3.999 0 0 1 12 15.998Zm7.847-10.406a1.44 1.44 0 1 1-2.879 0 1.44 1.44 0 0 1 2.879 0Z" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></path>
//                     </g>
//                     <defs style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                         <clipPath style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                             <path fill="#fff" d="M0 0h24v24H0z" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></path>
//                         </clipPath>
//                     </defs>
//                 </svg>
//             </div>
//             <div style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                 <svg width="24" height="24" fill="none" xmlns="http://www.w3.org/2000/svg" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                     <g clip-path="url(#svg1503935621_503_a)" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                         <path d="M12 0C5.373 0 0 5.373 0 12c0 5.628 3.875 10.35 9.101 11.647v-7.98H6.627V12H9.1v-1.58c0-4.084 1.849-5.978 5.859-5.978.76 0 2.072.15 2.608.298v3.324a15.38 15.38 0 0 0-1.386-.044c-1.967 0-2.728.745-2.728 2.683V12h3.92l-.673 3.667h-3.247v8.245C19.396 23.195 24 18.135 24 12c0-6.627-5.373-12-12-12Z" fill="#fff" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></path>
//                     </g>
//                     <defs style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                         <clipPath style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                             <path fill="#fff" d="M0 0h24v24H0z" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></path>
//                         </clipPath>
//                     </defs>
//                 </svg>
//             </div>
//             <div style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                 <svg width="24" height="24" fill="none" xmlns="http://www.w3.org/2000/svg" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                     <g clip-path="url(#svg1103582470_954_a)" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                         <path fill-rule="evenodd" clip-rule="evenodd" d="M12.01 0C5.369 0 0 5.408 0 12.1a12.09 12.09 0 0 0 8.212 11.477c.597.12.815-.26.815-.58 0-.281-.02-1.242-.02-2.244-3.34.721-4.036-1.443-4.036-1.443-.537-1.402-1.332-1.762-1.332-1.762-1.094-.741.08-.741.08-.741 1.212.08 1.849 1.242 1.849 1.242 1.073 1.842 2.803 1.322 3.5 1.001.098-.781.417-1.322.755-1.622-2.665-.28-5.468-1.323-5.468-5.97a4.74 4.74 0 0 1 1.232-3.245c-.119-.3-.537-1.543.12-3.205 0 0 1.014-.32 3.3 1.242a11.501 11.501 0 0 1 6.005 0c2.287-1.563 3.301-1.242 3.301-1.242.657 1.662.239 2.905.12 3.205.775.841 1.232 1.923 1.232 3.245 0 4.647-2.803 5.669-5.488 5.97.438.38.815 1.101.815 2.243 0 1.623-.02 2.925-.02 3.325 0 .32.22.702.816.581A12.09 12.09 0 0 0 24 12.1C24.02 5.41 18.63 0 12.01 0Z" fill="#fff" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></path>
//                     </g>
//                     <defs style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                         <clipPath style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                             <path fill="#fff" d="M0 0h24v24H0z" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></path>
//                         </clipPath>
//                     </defs>
//                 </svg>
//             </div>
//             <div style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                 <svg width="24" height="24" fill="none" xmlns="http://www.w3.org/2000/svg" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                     <path fill-rule="evenodd" clip-rule="evenodd" d="M12 0C5.375 0 0 5.375 0 12s5.375 12 12 12c6.612 0 12-5.375 12-12S18.612 0 12 0Zm7.926 5.531a10.202 10.202 0 0 1 2.317 6.378c-.338-.065-3.722-.755-7.132-.325-.079-.17-.144-.352-.222-.534a30.535 30.535 0 0 0-.676-1.484c3.774-1.536 5.492-3.748 5.713-4.035ZM12 1.771c2.603 0 4.985.975 6.794 2.576-.182.26-1.731 2.33-5.375 3.696-1.68-3.084-3.54-5.61-3.827-6A10.424 10.424 0 0 1 12 1.77Zm-4.36.962c.273.365 2.095 2.903 3.8 5.922-4.79 1.276-9.02 1.25-9.475 1.25.664-3.176 2.812-5.818 5.675-7.172Zm-5.896 9.28v-.312c.443.013 5.414.078 10.53-1.458.299.573.572 1.158.832 1.744-.13.039-.273.078-.403.117-5.284 1.705-8.096 6.364-8.33 6.755a10.226 10.226 0 0 1-2.629-6.846ZM12 22.256a10.18 10.18 0 0 1-6.286-2.16c.182-.378 2.264-4.387 8.043-6.404.026-.013.04-.013.065-.026 1.445 3.735 2.03 6.872 2.187 7.77-1.237.534-2.59.82-4.009.82Zm5.714-1.757c-.104-.625-.651-3.618-1.992-7.302 3.215-.507 6.026.326 6.378.443-.443 2.85-2.083 5.31-4.386 6.859Z" fill="#fff" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></path>
//                 </svg>
//             </div>
//             <div style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                 <svg width="24" height="24" fill="none" xmlns="http://www.w3.org/2000/svg" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                     <g clip-path="url(#svg764343192_640_a)" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                         <path d="M22.223 0H1.772C.792 0 0 .773 0 1.73v20.536C0 23.222.792 24 1.772 24h20.451c.98 0 1.777-.778 1.777-1.73V1.73C24 .773 23.203 0 22.223 0ZM7.12 20.452H3.558V8.995H7.12v11.457ZM5.34 7.434a2.064 2.064 0 1 1 0-4.125 2.063 2.063 0 0 1 0 4.125Zm15.112 13.018h-3.558v-5.57c0-1.326-.024-3.037-1.852-3.037-1.851 0-2.133 1.449-2.133 2.944v5.663H9.356V8.995h3.413v1.566h.047c.473-.9 1.636-1.852 3.365-1.852 3.605 0 4.27 2.372 4.27 5.457v6.286Z" fill="#fff" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></path>
//                     </g>
//                     <defs style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                         <clipPath style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                             <path fill="#fff" d="M0 0h24v24H0z" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></path>
//                         </clipPath>
//                     </defs>
//                 </svg>
//             </div>
//             <div style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                 <svg width="1250" height="3" viewBox="-1 -1 1250 3" fill="none" xmlns="http://www.w3.org/2000/svg" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                     <line y1="0.5" x2="1248" y2="0.5" stroke="#1C1C1C" style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></line>
//                 </svg>
//             </div>
//         </div>
//         <div style={{position: 'fixed', bottom: '0px', padding: '20px', width: '100%', display: 'flex', justifyContent: 'right', pointerEvents: 'none', zIndex: 314159, boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//             <div style={{opacity: 1, transform: 'none', pointerEvents: 'auto', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}><a href="https://www.framer.com" title="Framer - Custom website builder for designers, agencies and startups." style={{boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                     <div data-framer-name="Light" tabIndex="0" style={{-borderBottomWidth: '0px', -borderColor: 'rgba(0, 0, 0, 0)', -borderLeftWidth: '0px', -borderRightWidth: '0px', -borderStyle: 'solid', -borderTopWidth: '0px', backgroundColor: 'rgb(255, 255, 255)', borderRadius: '10px', boxShadow: 'rgba(0, 0, 0, 0.26) 0px 0.636953px 1.14652px -1.125px, rgba(0, 0, 0, 0.24) 0px 1.9316px 3.47689px -2.25px, rgba(0, 0, 0, 0.192) 0px 5.10612px 9.19102px -3.375px, rgba(0, 0, 0, 0.03) 0px 16px 28.8px -4.5px', cursor: 'pointer', opacity: 1, height: '36px', overflow: 'hidden', position: 'relative', width: '142px', willChange: 'transform', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                         <div style={{transform: 'translate(-50%, -50%)', opacity: 1, placeContent: 'center flex-start', alignItems: 'center', display: 'flex', flex: '0 0 auto', flexFlow: 'row nowrap', gap: '10px', height: '16px', left: '71px', overflow: 'visible', padding: '0px', position: 'absolute', top: '18px', width: 'min-content', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}>
//                             <div data-framer-component-type="SVG" data-framer-name="madeinframer" style={{imageRendering: 'pixelated', flexShrink: 0, backgroundSize: '100% 100%', backgroundImage: 'url("data:image/svg+xml', data: 'image/svg+xml', opacity: 1, flex: '0 0 auto', height: '16px', position: 'relative', width: '11px', zIndex: 2, boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></div>
//                             <div data-framer-component-type="SVG" role="img" aria-label="Framer - Custom site builder" aria-description="Made in Framer. The professional custom website design builder for startups, designers and agencies." style={{imageRendering: 'pixelated', flexShrink: 0, backgroundSize: '100% 100%', backgroundImage: 'url("data:image/svg+xml', data: 'image/svg+xml', opacity: 1, flex: '0 0 auto', height: '11px', position: 'relative', width: '92px', boxSizing: 'border-box', WebkitFontSmoothing: 'antialiased'}}></div>
//                         </div>
//                     </div>
//                 </a></div>
//         </div>
//     </body>
    
//     </html>
//   )
// }

// export default Index
